PhoneBookApplication/Models/Contact.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
namespace PhoneBookApplication.Models
{

    [Table("Contact")]
    public class Contact
    {

        [Key]
        [Required]
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }

        public string Department { get; set; }

        public string Titles { get; set; }

    }
}

PhoneBookApplication/Models/ErrorViewModel.cs
namespace PhoneBookApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PhoneBookApplication/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PhoneBookApplication.Data;
using PhoneBookApplication.Models;

namespace PhoneBookApplication.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _context;


        //constructor oluşturduk
        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index(string searchName, string searchSurname)
        {
            
            //Linq sorgusu

            var contacts = from m in _context.Contacts
                         select m;

            if (!String.IsNullOrEmpty(searchName))
            {
                contacts = contacts.Where(s => s.Name!.Contains(searchName)); //name içinde searchname değerini konrtol eder
            }

            if (!String.IsNullOrEmpty(searchSurname))
            {
                contacts = contacts.Where(s => s.Surname!.Contains(searchSurname));
            }

            return View(await contacts.ToListAsync());




        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound(); //sayfa bulunamadı
            }

            var contact = await _context.Contacts //contact tablosundan belirli bir kişi alır ve ilk eşleşen kaydı getirir
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact); //contact değişkeni içeren görünümü verir
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        

        [HttpPost] //formdan gelen bilgiler
        [ValidateAntiForgeryToken] //formdan gelen verilerin gerçekliğini doğrular
        public async Task<IActionResult> Create([Bind("Name,Surname,Email,PhoneNumber,Titles,Department")] Contact contact)
        {
           //Contact nesnesi Bind attributeü ile belirtilen özelliklere bağlanır
            
                _context.Add(contact); //contact nesnesine yeni veri eklenir
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
           
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id) // Edit işlemi için Controller tarafındaki bir action'ı temsil ediyor
        {
            if (id == null || _context.Contacts == null)
            { 
                //id’yi kontrol eder, context veri bağlantısını sağlıyor. http get isteği gelince sayfa görüntüler
                
                return NotFound();
            }

            var contact = await _context.Contacts.FindAsync(id); //FindAsync(id) metodu ile id ile eşleşen kişiyi arar
            if (contact == null)
            {
                return NotFound(); 
                                   //id ile eşleşen bir kişi bulunursa, bu kişiye ait verileri içeren bir görünümü(View) döndürür.
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost] //formdan gelen bilgiler
        [ValidateAntiForgeryToken] //formdan gelen verilerin gerçekliğini doğrular
        public async Task<IActionResult> Edit(int id, [Bind("Name,Surname,Email,PhoneNumber,Titles, Department")] Contact contact)
        { //id, düzenlenen kişinin kimliğini temsil eder. contact ise düzenlenmiş kişinin yeni verilerini içerir.

            try
                {
                    contact.ContactId = id; 
                    _context.Update(contact); //nesne güncellenir
                await _context.SaveChangesAsync(); //veri tabanına kaydedilir
            }
                catch (DbUpdateConcurrencyException) //başka kullanıcı güncelleme yapmış mı bakılır
            {
                    if (!ContactExists(contact.ContactId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index)); //kullanıcıyı index sayfasına yönlendirir

            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id) //bir iletişim bilgisini silmek için çağrılan asenkron bir kontrolör eylemidir
        {
            if (id == null || _context.Contacts == null) //siilinecek kişinin id'si null mı kontrol edilir
            {           
                return NotFound();
            }

            var contact = await _context.Contacts         //belirtilen id değerine sahip iletişim bilgisini veritabanından çekmeye çalışır.                                                               //await, asenkron bir işlem olduğunu belirtir v                                                               //bu işlem tamamlanana kadar beklenir.
           .FirstOrDefaultAsync(m => m.ContactId == id);  //await asenkron oluğunu gösterir
            if (contact == null)                           //bu işlem tamamlanana kadar beklenir. view'e aktarılır
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) //kişiyi silme işlemini gerçekleştirir
        {
            if (_context.Contacts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Contacts'  is null.");
            }
            var contact = await _context.Contacts.FindAsync(id);  //id ile eşleşen kişiyi bulmaya çalışır
                                                                 
                                                                 
            if (contact != null)
            {
                _context.Contacts.Remove(contact); //kişiyi siler
            }
            
            await _context.SaveChangesAsync();//veri tabanına kaydeder
            return RedirectToAction(nameof(Index)); //kullanıcyı sayfaya yönlendirir
        }

        private bool ContactExists(int id)  // belirtilen id ile eşleşen bir kişinin var olup olmadığını
                                            // kontrol eder ve bu bilgiyi bool bir değer olarak döndürür.
        {
          return (_context.Contacts?.Any(e => e.ContactId == id)).GetValueOrDefault();
        }
    }
}

PhoneBookApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBookApplication.Models;
using System.Diagnostics;

namespace PhoneBookApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PhoneBookApplication/Views/Contacts/Create.cshtml
@model PhoneBookApplication.Models.Contact

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Kişi Oluştur</title>
</head>
<body>

<h4>Yeni Kişi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="Name" class="control-label"></label>*@Ad
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Surname" class="control-label"></label>*@Soyad
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
                <div class="form-group">
                   @* <label asp-for="PhoneNumber" class="control-label"></label>*@Telefon Numarası
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
            </div>
                <div class="form-group">
                    @*<label asp-for="Titles" class="control-label"></label>*@Ünvan
                    <input asp-for="Titles" class="form-control" />
                    <span asp-validation-for="Titles" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @*<label asp-for="Department" class="control-label"></label>*@Departman
                    <input asp-for="Department" class="form-control" />
                    <span asp-validation-for="Department" class="text-danger"></span>
                </div>

            <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kişi Listesine Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

PhoneBookApplication/Views/Contacts/Delete.cshtml
@model PhoneBookApplication.Models.Contact 

@{
    Layout = "_Layout"; //şablon oluşturma
}
@*bu sayfa kişiyi silme işlemi için kullanılan bir onay sayfasıdır
*@<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Bu kişiyi silmek istediğinizden emin misiniz?</h3> /
<div>
   
    <hr />
        <dl class="row">
@*   dl etiketi, bir tanım listesi oluşturur. Bu durumda, Ad ve Soyad bilgilerini görüntülemek için kullanılır. 
    col-sm-2 ve col-sm-10 sınıfları, Bootstrap tarafından sağlanan grid sisteminin bir parçası olarak, 
    ekrana düzgün bir şekilde yerleştirmek için kullanılır.
*@
            <dt class="col-sm-2">
@*                dt içindekiler tanımlı terimleri temsil eder

*@           @* @Html.DisplayNameFor(model => model.Name)*@Ad 
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
                @*@Html.DisplayNameFor(model => model.Surname)*@Soyad // @*dd etiketleri bu terimlere ait değerleri 
                (@Html.DisplayFor(model => model.Name)) temsil eder. *@
                @*Html.DisplayFor metodu modeldeki belirli bir özelliği görüntülemek için kullanılır.*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
    </dl>
      @*  Bu form kullanıcıdan silme işlemini onaylamasını ister. asp-action attribute'ü, 
        formun hangi eyleme gönderileceğini belirtir. Silme işlemi için Delete’e gönderiyoruz*@.
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContactId" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a asp-action="Index">Kişi Listesine Geri Dön</a>
    </form>
</div>
</body>
</html>

PhoneBookApplication/Views/Contacts/Details.cshtml
@model PhoneBookApplication.Models.Contact

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Kişi Bilgisi</title>
</head>
<body>

    <div>
        <h4 class="alert alert-info">Kişi</h4>

        <dl class="alert alert-secondary">
        <dt class = "col-sm-2">
           @* @Html.DisplayNameFor(model => model.Name)*@Ad
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
           @* @Html.DisplayNameFor(model => model.Surname)*@Soyad
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
            <dt class="col-sm-2">
                @*@Html.DisplayNameFor(model => model.PhoneNumber)*@Telefon Numarası
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
               @* @Html.DisplayNameFor(model => model.Titles)*@Ünvan
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Titles)
            </dd>
            <dt class="col-sm-2">
               @* @Html.DisplayNameFor(model => model.Department)*@Departman
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Department)
            </dd>
    </dl>
</div>
<div>
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.ContactId">Düzenle</a> |
        @*//controller içindeki edite bağlıdır*@
        <a class="btn btn-secondary" asp-action="Index">Kişi Listesine Geri Dön</a>
</div>
</body>
</html>

PhoneBookApplication/Views/Contacts/Edit.cshtml
@model PhoneBookApplication.Models.Contact ///Sayfanın kullanacağı modeli belirtir. Contact sınıfının bir örneğini kullanır.

@{
    Layout = "_Layout"; /*Arayüz için kullandığımız layoutu yani şablonu belirtir.*/
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" /> @*mobil cihaz alan uyumu*@
    <title>Düzenle</title>
</head>
<body>

<h4>Kişi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div> @*doğrulama işlemi*@
                <input type="hidden" asp-for="ContactId" /> @*gizlenmiş kişi id’si*@
               
                @* kişi bilgisi düzenlemek için bir form*@
                <div class="form-group">
                   
                @*<label asp-for="Name" class="control-label"></label>*@Ad
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
               @* <label asp-for="Surname" class="control-label"></label>*@Soyad
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="PhoneNumber" class="control-label"></label>*@Telefon Numarası
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
               @* <label asp-for="Titles" class="control-label"></label>*@Ünvan
                <input asp-for="Titles" class="form-control" />
                <span asp-validation-for="Titles" class="text-danger"></span>
            </div>
            <div class="form-group">
               @* <label asp-for="Department" class="control-label"></label>*@Departman
                    <input asp-for="Department" class="form-control" />
                    <span asp-validation-for="Department" class="text-danger"></span>

            </div>
                <div class="form-group">
                    @*kaydet butonu için input*@
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

    <div>
         @*kişi listesine geri dön, buton gibi olan bir bağlantıdır*@
    <a class="btn btn-secondary" asp-action="Index">Kişi Listesine Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} 
}
@* Sayfanın sonundaki script'leri içeren _ValidationScriptsPartial partial view'inin eklenmesidir. 
    Bu script'ler genellikle form doğrulama (validation) işlemleri için gerekli olan 
    JavaScript kütüphanelerini ve kodlarını içerir.
*@</body>
</html>

PhoneBookApplication/Views/Contacts/Index.cshtml
@model IEnumerable<PhoneBookApplication.Models.Contact>

@{
    Layout = "_Layout";
}
<style>
    .a{
        color=red;
    }
</style>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Kişi Listesi
    </title>
</head>
<body>
<p> 
    <a class="btn btn-primary" asp-action="Create">Yeni Kişi Oluştur</a>
</p>

       @* //arama temizleme işlemi*@
    <form asp-controller="Contacts" asp-action="Index">
        <p>
            Ad: <input type="text" name="searchName" />
            Soyad: <input type="text" name="searchSurname" />
            <input type="submit" value="Ara" />
        <input type="submit" value="Temizle" />
        </p>
    </form>
   
    @* kişi tablosu modeli aaktardık*@
    
    
    
<table class="table table-striped table-bordered">

    <thead class="thead-dark">
        <tr>
            <th scope="col">
               @*// @Html.DisplayNameFor(model => model.Name)*@ Ad
            </th>
            <th scope="col">
               @* @Html.DisplayNameFor(model => model.Surname)*@ Soyad
            </th>
            
            <th scope="col">
                    @Html.DisplayNameFor(model => model.Email)
            </th>
            <th scope="col">
                   @* @Html.DisplayNameFor(model => model.PhoneNumber)*@ Telefon Numarası
            </th>
             <th scope="col">
                   @* @Html.DisplayNameFor(model => model.Titles)*@ Ünvan
            </th>
                <th scope="col">
                    @* @Html.DisplayNameFor(model => model.Department*@ Departman
                </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
            @foreach (var item in Model)
            {
               @* Sayfada görüntüleme işlemleri*@
               <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                        @Html.DisplayFor(modelItem => item.Titles)
            </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department)
                    </td>
            <td>
@*          
    index sayfasındaki her bir kişi için kişiyi düzenle sil kişi bilgisi bağlantılarını bulundurur
*@
                 @* düzenleme için edit actionını çağırırız*@
                <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.ContactId">Kişiyi Düzenle</a> @*| düzenleme için edit actionını çağırırız*@
                <a class="btn btn-light" asp-action="Details" asp-route-id="@item.ContactId">Kişi Bilgisi</a>@* |*@
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ContactId">Sil</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

PhoneBookApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PhoneBookApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Telefon Rehberi</title> @*sayfanın başlığı*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBookApplication.styles.css" asp-append-version="true" /> @*özel stil dosyası*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*Aşağıdaki bağlantı, sayfanın başlığını temsil eder ve "Contacts" controller'ındaki "Index" action'ına yönlendirir.*@
                <a class="navbar-brand" asp-area="" asp-controller="Contacts" asp-action="Index">Telefon Rehberi</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Kişi Listesi</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() @*sayfa içeriğini alır*@
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Telefon Rehberi - Zişan ve Nisa @*sayfanın alt bilgisi, tarih ve isim içerir*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

   @* Bu etiket, sayfanın içeriğinde bir bölüm oluşturulmuşsa, bu bölümdeki scriptleri çağırır. 
    Bu layout sayfası kod tekrarını önler ve tutarlı bir görünüm sağlar. 
    Bootstrap ve jQuery gibi kütüphaneleri kullanarak mobil uyumluluk ve kullanıcı arayüzü geliştirmeleri de sağlanmıştır.*@
</body>
</html>